stages:
    - build
    # - deploy

image: node:lts

cache:
    paths:
        - node_modules/

before_script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl

build job:
    stage: build
    script:
        - yarn install
        - yarn cache clean
        - yarn build
    artifacts:
        paths:
            - build/

# deploy_preview:
#     stage: deploy
#     except:
#         - main
#     script:
#         - npm install --global vercel
#         - vercel pull --yes --environment=preview --token=$VERCEL_TOKEN
#         - vercel build --token=$VERCEL_TOKEN
#         - vercel deploy --prebuilt  --token=$VERCEL_TOKEN

# deploy_production:
#     stage: deploy
#     only:
#         - main
#     script:
#         - npm install --global vercel
#         - vercel pull --yes --environment=production --token=$VERCEL_ORG_ID --force
#         - vercel build --prod --token=$VERCEL_ORG_ID
#         - vercel deploy --prebuilt --prod --token=$VERCEL_ORG_ID