stages:
    - build
    - deploy

image: node:lts

cache:
    paths:
        - node_modules/

before_script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl

build job:
    stage: build
    script:
        - yarn install
        - yarn build
    artifacts:
        paths:
            - build/

deploy job:
    stage: deploy
    only:
        - main
    environment:
        name: main
        url: https://edwin-vite-39o1.vercel.app
    script:
        - yarn global add vercel
        - DEPLOYMENT_URL=$(VERCEL_ORG_ID=$VERCEL_ORG_ID VERCEL_PROJECT_ID=$VERCEL_PROJECT_ID vercel --confirm -t $VERCEL_TOKEN --prod)
