stages:
    - build

image: node:lts

cache:
    paths:
        - node_modules/

before_script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl

build job:
    stage: build
    script:
        - yarn install
        - yarn build
    artifacts:
        paths:
            - build/
