stages:
    - build
    - test
    - deploy

image: node:lts

cache:
    paths:
        - node_modules/

before_script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl

build job:
    stage: build
    script:
        - yarn install
        - yarn build
    artifacts:
        paths:
            - build/

test job:
    stage: test
    script:
        - yarn test

deploy staging:
    image: ruby
    stage: deploy
    environment:
        name: staging
        url: https://edwin-erp.herokuapp.com/
    only:
        - staging
    script:
        - gem install faraday -v 1.10.0
        - dpl --provider=heroku --app=$HEROKU_APP_STAGING --api-key=$HEROKU_API_KEY
